-- Migration: user_roles table + custom_access_token_hook for JWT-based RBAC
-- Based on: https://supabase.com/docs/guides/api/custom-claims-and-role-based-access-control-rbac
--
-- Run in the Supabase SQL editor, then:
--   1. Go to Authentication → Hooks
--   2. Add hook → Custom Access Token → Postgres function → public.custom_access_token_hook
--   3. Save
--
-- To grant admin access to a user:
--   Dashboard → Table Editor → user_roles → Insert row: { user_id: <uuid>, role: 'admin' }

-- ============================================================
-- 1. Role enum
-- ============================================================
create type public.app_role as enum ('admin');

-- ============================================================
-- 2. user_roles table (dashboard-editable)
-- ============================================================
create table public.user_roles (
  id      bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role    public.app_role not null,
  unique (user_id, role)
);

-- ============================================================
-- 3. Auth hook function
--    Runs before every JWT is issued. Queries user_roles and
--    injects the role as a top-level 'user_role' claim in the JWT.
--    NOTE: this claim does NOT appear in supabase.auth.getUser()
--    responses — it lives only in the JWT payload itself.
-- ============================================================
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
  declare
    claims    jsonb;
    user_role public.app_role;
  begin
    select role into user_role
    from public.user_roles
    where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_role is not null then
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
      claims := jsonb_set(claims, '{user_role}', 'null');
    end if;

    event := jsonb_set(event, '{claims}', claims);
    return event;
  end;
$$;

-- ============================================================
-- 4. Permissions
--    supabase_auth_admin runs the hook — it needs execute on
--    the function and read on user_roles. Everything else revoked.
-- ============================================================
grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;

grant all on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;

-- ============================================================
-- 5. RLS
--    supabase_auth_admin is not the service role, so it needs
--    an explicit policy to read user_roles during hook execution.
-- ============================================================
alter table public.user_roles enable row level security;

create policy "Allow auth admin to read user roles"
  on public.user_roles
  as permissive
  for select
  to supabase_auth_admin
  using (true);
